background_image metro_darkened.png
background_image_layout cscaled

map ctrl+left neighboring_window left
map ctrl+right neighboring_window right
map ctrl+up neighboring_window up
map ctrl+down neighboring_window down

cursor_shape block
shell_integration no-cursor

scrollback_pager nvim -c "set nonumber nolist showtabline=0 foldcolumn=0 laststatus=0" -c "autocmd TermOpen * normal G" -c "map <C-c> :qa!<CR>" -c "tmap <C-c> <C-\\><C-n>:qa!<CR>" -c "silent write! /tmp/kitty_scrollback_buffer | te cat /tmp/kitty_scrollback_buffer - "
map alt+s show_scrollback

term xterm-256color

tab_title_template {session_name} {title}
